corrected shellcheck issues and disabled others

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,25 +1,32 @@
 #!/usr/bin/env sh
 
 # Install script for dotfiles
+src_dir="${HOME}/dotfiles/src/${1}"
 # Check if the first argument is either 'zsh' or 'bash'
 if [ "$1" != "zsh" ] && [ "$1" != "bash" ]; then
-  echo -e "The $1 shell is unrecognized. The first argument must be either 'zsh' or 'bash'."
+  echo "Installation Error:: The first argument must be either 'zsh' or 'bash'."
   exit 1
 fi
-dotfiles_dir="${HOME}/dotfiles"
-src_dir="${dotfiles_dir}/src/${1}"
+ident=$(grep "Dotfile installation" < "${HOME}/.zshrc" | wc -c)
+if [ "$ident" -gt 0 ]; then
+  # shellcheck disable=SC1090
+  . "./src/${1}/functions"
+  wmsg "Dotfiles are already installed. Delete the existing installation and try again."
+  exit 1
+fi
 update_rc_file() {
 cat <<EOF >> "${HOME}/.zshrc"
+# Dotfile installation
 # Source dotfiles_dirs
-source "${src_dir}/functions.sh"
-source "${src_dir}/aliases.sh"
+source "${src_dir}/functions"
+source "${src_dir}/aliases"
 set -a
 source "${src_dir}/env.env"
 # Add custom dotfiles
 # Add functions
-[ -f ${HOME}/${1}-src/functions.sh ] && source ${HOME}/${1}-src/functions.sh
+[ -f ${HOME}/${1}-src/functions ] && source ${HOME}/${1}-src/functions
 # Add aliases
-[ -f ${HOME}/${1}-src/aliases.sh ] && source ${HOME}/${1}-src/aliases.sh
+[ -f ${HOME}/${1}-src/aliases ] && source ${HOME}/${1}-src/aliases
 # Add environment variables
 [ -f ${HOME}/${1}-src/env.env ] && source ${HOME}/${1}-src/env.env
 [ -f ${HOME}/${1}-src/ecr.env.ecr ] && decrypt ${HOME}/${1}-src/ecr.env.ecr
@@ -27,17 +34,9 @@ source "${src_dir}/env.env"
 set +a
 EOF
 }
-# Check if the dotfiles directory exists otherwise clone the repo
-if [ ! -d "$dotfiles_dir" ]; then
-    cd "$HOME" || exit
-    git clone git@github.com:ec-intl/dotfiles.git
-    cd "$dotfiles_dir" || exit
-fi
-# Pull the latest changes from the repo
-cd "$dotfiles_dir" || exit
 git pull origin main
-source "${src_dir}/functions.sh"
+# shellcheck disable=SC1090
+. "./src/${1}/functions"
 imsg "Installing ${1}...\n"
 update_rc_file "$1"
 kmsg "Installation complete."
-
diff --git a/src/zsh/functions b/src/zsh/functions
--- a/src/zsh/functions
+++ b/src/zsh/functions
@@ -1,21 +1,23 @@
+#! /usr/bin/env sh
+
 # Print color coded messages
 msg() {
   timestamp=$(date '+%Y-%m-%d %H:%M:%S')
   case $1 in
     fail)
-      echo "\n$timestamp \033[31m[  FAILURE  ]\033[0m $2\n"
+      printf "\n%s \033[1;31m[  FAILURE  ]\033[0m %s\n\n" "$timestamp" "$2"
       ;;
     ok)
-      echo "\n$timestamp \033[32m[  SUCCESS  ]\033[0m $2\n"
+      printf "\n%s \033[1;32m[  SUCCESS  ]\033[0m %s\n\n" "$timestamp" "$2"
       ;;
     warn)
-      echo "$timestamp \033[33m[  WARNING  ]\033[0m $2"
+      printf "\n%s \033[1;33m[  WARNING  ]\033[0m %s\n\n" "$timestamp" "$2"
       ;;
     info)
-      echo "$timestamp \033[34m[INFORMATION]\033[0m $2"
+      printf "\n%s \033[1;34m[INFORMATION]\033[0m %s\n\n" "$timestamp" "$2"
       ;;
     *)
-      echo "$timestamp [  NOTICE  ] $2"
+      printf "\n%s [  NOTICE  ] %s\n\n"  "$timestamp" "$2"
       ;;
   esac
 }
@@ -38,14 +40,14 @@ greet() {
   timestamp=$(date '+%Y-%m-%d %H:%M:%S')
   HOUR=$(date +%H)
   # If the hour is less than 12, it's morning
-  if [ $HOUR -lt 12 ]; then
-    echo "$timestamp Good Morning"
+  if [ "$HOUR" -lt 12 ]; then
+    printf "%s Good Morning" "$timestamp"
     # If the hour is between 12 and 18, it's afternoon
-  elif [ $HOUR -lt 18 ]; then
-    echo "$timestamp Good Afternoon"
+  elif [ "$HOUR" -lt 18 ]; then
+    printf "%s Good Afternoon" "$timestamp"
     # Otherwise, it's evening
   else
-    echo "$timestamp Good Evening"
+    printf "%s Good Evening" "$timestamp"
   fi
 }
 
@@ -96,7 +98,9 @@ make_default_directories() {
       mkdir -p "${HOME}/$1"
     fi
   }
+  # shellcheck disable=SC3030
   directories=( Downloads bin lib src )
+  # shellcheck disable=SC3054
   for dir in "${directories[@]}"; do
     makedir "$dir"
   done
@@ -105,7 +109,8 @@ make_default_directories() {
 
 # Make a python virtual environment
 python_venv() {
-  python -m venv "$1" && source "$1/bin/activate"
+  # shellcheck disable=SC1091
+  python -m venv "$1" && . "$1/bin/activate"
 }
 
 
@@ -114,13 +119,15 @@ encrypt() {
  imsg "Encrypting $1..."
  openssl aes-256-cbc -pbkdf2 -e -in "$1" -out "$1".ecr
  [ -f "$1.ecr" ] && rm -f "$1" && chmod 0700 "$1.ecr" && kmsg "$1 encrypted successfully."
- [ ! $? || ! -f "$1.ecr"] && emsg "Encryption failed."
+ if [ ! $? ] || [ ! -f "$1.ecr" ]; then
+  emsg "Encryption failed."
+ fi
 }
 
-
+# Decrypt file using openssl
 decrypt() {
-  imsg "Decrypting $1..."
-  outfile=`echo $1 | sed 's/\.ecr$//'`
+  imsg "Decrypting ${1}..."
+  outfile=$(sed 's/\.ecr$//' < "$1")
   openssl aes-256-cbc -pbkdf2 -d -in "$1" -out "$outfile"
   [ -f "$outfile" ] && kmsg "Decryption successful."
   [ ! $? ] && emsg "Decryption failed"
@@ -131,13 +138,15 @@ decrypt() {
 setenv() {
   imsg "Setting environment variables from file: $1"
   set -a
-  [ -f "$1" ] && source "$1" && kmsg "Environment successfully set." && set +a
+  # shellcheck disable=SC1090
+  [ -f "$1" ] && . "$1" && kmsg "Environment successfully set." && set +a
   [ ! $? ] || [ ! -f "$1" ] && emsg "An error occurred. Likely file not found." && set +a
 }
 
 
 gen_secret_key() {
-  echo `openssl rand -base64 32`
+  # shellcheck disable=SC2005
+  echo "$(openssl rand -base64 32)"
 }
 
 
